### ISSUE TITLE
Tutorial-1 3b model is returning gibberish

### ISSUE THREAD

**Issue by sincRK** [marrlab/HistoGPT#15]
I've tried a few things with your models and their usage in the tutorial-1.ipynb but can't get the big model to produce something sensible. The smaller model produces sensible output.

Example: From Features extracted by CLAM from example NDPI
3b
Final diagnosis: after Two advanced to 
and artery-and 37 PA 202 Random same We 
CDDP has adults. technconcentration We 
tual disproportionately-is observations 
IK She pulse memory has adults of 
extended cell Differences cells and 
Differences-and SETTING. Component 
concentration We o at is did-1A2 of ib 
Obfew labelled has sample of been than 
ortholog 량in master; and Considering. 
blood sample Mis Based Outcome Cancer 
moments basis to and Differences artery.
 medication of early at is outcomes 
opainful flow.

1b
Final diagnosis: Basal cell carcinoma. 
Critical findings: The diagnosis is an 
ulcerated solid basal cell carcinoma 
with a tumor thickness of 0. 3 mm, 
extending to the edge of the cut. 
Microscopic findings: A punch biopsy 
reveals a completely ulcerated 
epidermis, and a centrally located 
hemispheric tumor with proliferating 
basaloid tumor cell clusters extending 
into the middle corium. There is a focal
 cystic arrangement of tumor cells, with
 peritumoral distinct palisades. Focal 
adenoid differentiation is observed. A 
cellular inflammatory stroma reaction is
 present.

Example: From downloaded Features
3b
Final diagnosis: after assay not 
progressive abr. texts BP. 
technconcentration We tual 
disproportionately-is TMmemory has 
adults of to is has) theory thirds. 
<unk>AIS Based. Random same We CDDP has 
adults. Component concentration We tool 
and pretreatment-and Considering of 
ortholog 량@-@ Obfew labelled has myelin 
significantly after it to relationships 
mangin ranged) plasticity incisional by 
Outcome Cancer <unk>) functional 
prospective serious to and Both pass. 
conditional opainful flow.

1b
Final diagnosis: Basal cell carcinoma. 
Critical findings: The diagnosis is 
consistent with a superficial basal cell
 carcinoma with a tumor thickness of 0. 
5 mm. The specimen is exact in toto. 
Microscopic findings: In the epidermis, 
endophytic proliferations of basaloid 
cell strands are observed in solid nest 
and strand-shaped formations, featuring 
palisade-like core positions in the 
peripheral zones. There is a cellular 
inflammatory stroma reaction.

Can you share a working example for the larger model together with the inference settings?

**Comment by manuel-tran** [comment]
Hi,

Have you already changed the tokenizer? I think that is most likely the cause of the problem. Everything else is the same.

```python
tokenizer = BioGptTokenizer.from_pretrained("microsoft/biogpt-large")

**Comment by sincRK** [comment]
Missed it, thanks!
